name: Fetch News Feeds

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Hit feed-fetch endpoint
        run: curl "https://flashfeed-site.vercel.app/api/cron/fetch-feeds?key=${{ secrets.CRON_SECRET }}"
