name: Fetch News Feeds

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Hit feed-fetch endpoint
        run: curl -X POST "https://flashfeed-fh5rilw4a-mrinal-dev.vercel.app//api/cron/fetch-feeds?key=x-cron-secret"
